# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user__settings__branding_api import UserSettingsBrandingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserSettingsBrandingApi(unittest.TestCase):
    """UserSettingsBrandingApi unit test stubs"""

    def setUp(self):
        self.api = UserSettingsBrandingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_branding_content_branding_logo(self):
        """Test case for branding_content_branding_logo

        Get the current user's branding logo  # noqa: E501
        """
        pass

    def test_branding_content_branding_logo_update(self):
        """Test case for branding_content_branding_logo_update

        Update the current user's branding logo.  # noqa: E501
        """
        pass

    def test_branding_logo_remove(self):
        """Test case for branding_logo_remove

        Remove the current user's branding logo.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
