# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups(self):
        """Test case for groups

        TODO  # noqa: E501
        """
        pass

    def test_groups_attributes(self):
        """Test case for groups_attributes

        TODO  # noqa: E501
        """
        pass

    def test_groups_branding_logo_remove(self):
        """Test case for groups_branding_logo_remove

        TODO  # noqa: E501
        """
        pass

    def test_groups_common_edit(self):
        """Test case for groups_common_edit

        TODO  # noqa: E501
        """
        pass

    def test_groups_content_groups_branding_logo(self):
        """Test case for groups_content_groups_branding_logo

        Get the group's branding logo  # noqa: E501
        """
        pass

    def test_groups_content_groups_branding_logo_update(self):
        """Test case for groups_content_groups_branding_logo_update

        Update the group's branding logo.  # noqa: E501
        """
        pass

    def test_groups_details(self):
        """Test case for groups_details

        TODO  # noqa: E501
        """
        pass

    def test_groups_users_add(self):
        """Test case for groups_users_add

        TODO  # noqa: E501
        """
        pass

    def test_groups_users_edit(self):
        """Test case for groups_users_edit

        TODO  # noqa: E501
        """
        pass

    def test_groups_users_remove(self):
        """Test case for groups_users_remove

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
