# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.o_auth_2_api import OAuth2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuth2Api(unittest.TestCase):
    """OAuth2Api unit test stubs"""

    def setUp(self):
        self.api = OAuth2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth2_device_code(self):
        """Test case for oauth2_device_code

        OAuth 2.0 Device Code Endpoint  # noqa: E501
        """
        pass

    def test_oauth2_token(self):
        """Test case for oauth2_token

        OAuth 2.0 Token Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
