# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.job_file_dest_errors import JobFileDestErrors  # noqa: E501
from swagger_client.rest import ApiException


class TestJobFileDestErrors(unittest.TestCase):
    """JobFileDestErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobFileDestErrors(self):
        """Test JobFileDestErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.job_file_dest_errors.JobFileDestErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
