# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.app_passwords_api import AppPasswordsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAppPasswordsApi(unittest.TestCase):
    """AppPasswordsApi unit test stubs"""

    def setUp(self):
        self.api = AppPasswordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_passwords_generate(self):
        """Test case for app_passwords_generate

        TODO  # noqa: E501
        """
        pass

    def test_app_passwords_list(self):
        """Test case for app_passwords_list

        TODO  # noqa: E501
        """
        pass

    def test_app_passwords_revoke(self):
        """Test case for app_passwords_revoke

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
