# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mounts__receivers_api import MountsReceiversApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMountsReceiversApi(unittest.TestCase):
    """MountsReceiversApi unit test stubs"""

    def setUp(self):
        self.api = MountsReceiversApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_receivers(self):
        """Test case for receivers

        TODO  # noqa: E501
        """
        pass

    def test_receivers_create(self):
        """Test case for receivers_create

        TODO  # noqa: E501
        """
        pass

    def test_receivers_delete(self):
        """Test case for receivers_delete

        TODO  # noqa: E501
        """
        pass

    def test_receivers_details(self):
        """Test case for receivers_details

        TODO  # noqa: E501
        """
        pass

    def test_receivers_remove_password(self):
        """Test case for receivers_remove_password

        TODO  # noqa: E501
        """
        pass

    def test_receivers_reset_password(self):
        """Test case for receivers_reset_password

        TODO  # noqa: E501
        """
        pass

    def test_receivers_set_alert(self):
        """Test case for receivers_set_alert

        TODO  # noqa: E501
        """
        pass

    def test_receivers_set_message(self):
        """Test case for receivers_set_message

        TODO  # noqa: E501
        """
        pass

    def test_receivers_set_password(self):
        """Test case for receivers_set_password

        TODO  # noqa: E501
        """
        pass

    def test_receivers_set_url_hash(self):
        """Test case for receivers_set_url_hash

        TODO  # noqa: E501
        """
        pass

    def test_receivers_set_validity(self):
        """Test case for receivers_set_validity

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
