# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user__bookmarks_api import UserBookmarksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserBookmarksApi(unittest.TestCase):
    """UserBookmarksApi unit test stubs"""

    def setUp(self):
        self.api = UserBookmarksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bookmarks(self):
        """Test case for bookmarks

        TODO  # noqa: E501
        """
        pass

    def test_bookmarks_create(self):
        """Test case for bookmarks_create

        TODO  # noqa: E501
        """
        pass

    def test_bookmarks_edit(self):
        """Test case for bookmarks_edit

        TODO  # noqa: E501
        """
        pass

    def test_bookmarks_remove(self):
        """Test case for bookmarks_remove

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
