# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mounts__comments_api import MountsCommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMountsCommentsApi(unittest.TestCase):
    """MountsCommentsApi unit test stubs"""

    def setUp(self):
        self.api = MountsCommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_comments(self):
        """Test case for comments

        TODO  # noqa: E501
        """
        pass

    def test_comments_delete(self):
        """Test case for comments_delete

        TODO  # noqa: E501
        """
        pass

    def test_comments_details(self):
        """Test case for comments_details

        TODO  # noqa: E501
        """
        pass

    def test_comments_new(self):
        """Test case for comments_new

        TODO  # noqa: E501
        """
        pass

    def test_comments_range(self):
        """Test case for comments_range

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
