# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user__settings_api import UserSettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserSettingsApi(unittest.TestCase):
    """UserSettingsApi unit test stubs"""

    def setUp(self):
        self.api = UserSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settings_language(self):
        """Test case for settings_language

        Get current preferred language  # noqa: E501
        """
        pass

    def test_settings_language_edit(self):
        """Test case for settings_language_edit

        Update current preferred language  # noqa: E501
        """
        pass

    def test_settings_notifications(self):
        """Test case for settings_notifications

        Get notifications settings  # noqa: E501
        """
        pass

    def test_settings_notifications_edit(self):
        """Test case for settings_notifications_edit

        Update notification settings  # noqa: E501
        """
        pass

    def test_settings_security(self):
        """Test case for settings_security

        Get security settings  # noqa: E501
        """
        pass

    def test_settings_security_edit(self):
        """Test case for settings_security_edit

        Update security settings  # noqa: E501
        """
        pass

    def test_settings_seen(self):
        """Test case for settings_seen

        Get seen settings  # noqa: E501
        """
        pass

    def test_settings_seen_edit(self):
        """Test case for settings_seen_edit

        Update seen settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
