# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user(self):
        """Test case for user

        Current user info  # noqa: E501
        """
        pass

    def test_user_attributes(self):
        """Test case for user_attributes

        TODO  # noqa: E501
        """
        pass

    def test_user_authenticated(self):
        """Test case for user_authenticated

        TODO  # noqa: E501
        """
        pass

    def test_user_change_email(self):
        """Test case for user_change_email

        TODO  # noqa: E501
        """
        pass

    def test_user_change_password(self):
        """Test case for user_change_password

        TODO  # noqa: E501
        """
        pass

    def test_user_edit(self):
        """Test case for user_edit

        Update current user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
