# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mounts__bundle_api import MountsBundleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMountsBundleApi(unittest.TestCase):
    """MountsBundleApi unit test stubs"""

    def setUp(self):
        self.api = MountsBundleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bundle(self):
        """Test case for bundle

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
