# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.shared_api import SharedApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSharedApi(unittest.TestCase):
    """SharedApi unit test stubs"""

    def setUp(self):
        self.api = SharedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_shared(self):
        """Test case for shared

        TODO  # noqa: E501
        """
        pass

    def test_shared_details(self):
        """Test case for shared_details

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
