# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.config_localization_language import ConfigLocalizationLanguage  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigLocalizationLanguage(unittest.TestCase):
    """ConfigLocalizationLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigLocalizationLanguage(self):
        """Test ConfigLocalizationLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.config_localization_language.ConfigLocalizationLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
