# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mounts_api import MountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMountsApi(unittest.TestCase):
    """MountsApi unit test stubs"""

    def setUp(self):
        self.api = MountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mounts(self):
        """Test case for mounts

        List of places and shared folders.  # noqa: E501
        """
        pass

    def test_mounts_delete(self):
        """Test case for mounts_delete

        TODO  # noqa: E501
        """
        pass

    def test_mounts_details(self):
        """Test case for mounts_details

        TODO  # noqa: E501
        """
        pass

    def test_mounts_edit(self):
        """Test case for mounts_edit

        TODO  # noqa: E501
        """
        pass

    def test_mounts_groups_add(self):
        """Test case for mounts_groups_add

        TODO  # noqa: E501
        """
        pass

    def test_mounts_groups_remove(self):
        """Test case for mounts_groups_remove

        TODO  # noqa: E501
        """
        pass

    def test_mounts_reauth(self):
        """Test case for mounts_reauth

        TODO  # noqa: E501
        """
        pass

    def test_mounts_submounts_create(self):
        """Test case for mounts_submounts_create

        TODO  # noqa: E501
        """
        pass

    def test_mounts_users_add(self):
        """Test case for mounts_users_add

        TODO  # noqa: E501
        """
        pass

    def test_mounts_users_edit(self):
        """Test case for mounts_users_edit

        TODO  # noqa: E501
        """
        pass

    def test_mounts_users_remove(self):
        """Test case for mounts_users_remove

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
