# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user__app_config_api import UserAppConfigApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAppConfigApi(unittest.TestCase):
    """UserAppConfigApi unit test stubs"""

    def setUp(self):
        self.api = UserAppConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_app_config(self):
        """Test case for user_app_config

        Application configuration and feature flags for the current user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
