# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiErrorDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'extra': 'dict(str, dict(str, object))',
        'message': 'str'
    }

    attribute_map = {
        'code': 'code',
        'extra': 'extra',
        'message': 'message'
    }

    def __init__(self, code=None, extra=None, message=None):  # noqa: E501
        """ApiErrorDetails - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._extra = None
        self._message = None
        self.discriminator = None
        self.code = code
        if extra is not None:
            self.extra = extra
        self.message = message

    @property
    def code(self):
        """Gets the code of this ApiErrorDetails.  # noqa: E501

        Code is the application relevant detail defined in the API or a common list.  # noqa: E501

        :return: The code of this ApiErrorDetails.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ApiErrorDetails.

        Code is the application relevant detail defined in the API or a common list.  # noqa: E501

        :param code: The code of this ApiErrorDetails.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def extra(self):
        """Gets the extra of this ApiErrorDetails.  # noqa: E501

        Extra is extra error info.  # noqa: E501

        :return: The extra of this ApiErrorDetails.  # noqa: E501
        :rtype: dict(str, dict(str, object))
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this ApiErrorDetails.

        Extra is extra error info.  # noqa: E501

        :param extra: The extra of this ApiErrorDetails.  # noqa: E501
        :type: dict(str, dict(str, object))
        """

        self._extra = extra

    @property
    def message(self):
        """Gets the message of this ApiErrorDetails.  # noqa: E501

        Message is the explanation of the error which can be shown to the client user.  # noqa: E501

        :return: The message of this ApiErrorDetails.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ApiErrorDetails.

        Message is the explanation of the error which can be shown to the client user.  # noqa: E501

        :param message: The message of this ApiErrorDetails.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiErrorDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiErrorDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
