# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BundleFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bookmark': 'BundleBookmark',
        'content_type': 'str',
        'hash': 'str',
        'link': 'Link',
        'modified': 'int',
        'mount': 'Mount',
        'mount_path': 'str',
        'name': 'str',
        'receiver': 'Receiver',
        'size': 'int',
        'tags': 'dict(str, list[str])',
        'type': 'str',
        'vault_repo': 'BundleVaultRepo'
    }

    attribute_map = {
        'bookmark': 'bookmark',
        'content_type': 'contentType',
        'hash': 'hash',
        'link': 'link',
        'modified': 'modified',
        'mount': 'mount',
        'mount_path': 'mountPath',
        'name': 'name',
        'receiver': 'receiver',
        'size': 'size',
        'tags': 'tags',
        'type': 'type',
        'vault_repo': 'vaultRepo'
    }

    def __init__(self, bookmark=None, content_type=None, hash=None, link=None, modified=None, mount=None, mount_path=None, name=None, receiver=None, size=None, tags=None, type=None, vault_repo=None):  # noqa: E501
        """BundleFile - a model defined in Swagger"""  # noqa: E501
        self._bookmark = None
        self._content_type = None
        self._hash = None
        self._link = None
        self._modified = None
        self._mount = None
        self._mount_path = None
        self._name = None
        self._receiver = None
        self._size = None
        self._tags = None
        self._type = None
        self._vault_repo = None
        self.discriminator = None
        if bookmark is not None:
            self.bookmark = bookmark
        self.content_type = content_type
        if hash is not None:
            self.hash = hash
        if link is not None:
            self.link = link
        self.modified = modified
        if mount is not None:
            self.mount = mount
        if mount_path is not None:
            self.mount_path = mount_path
        self.name = name
        if receiver is not None:
            self.receiver = receiver
        self.size = size
        self.tags = tags
        self.type = type
        if vault_repo is not None:
            self.vault_repo = vault_repo

    @property
    def bookmark(self):
        """Gets the bookmark of this BundleFile.  # noqa: E501


        :return: The bookmark of this BundleFile.  # noqa: E501
        :rtype: BundleBookmark
        """
        return self._bookmark

    @bookmark.setter
    def bookmark(self, bookmark):
        """Sets the bookmark of this BundleFile.


        :param bookmark: The bookmark of this BundleFile.  # noqa: E501
        :type: BundleBookmark
        """

        self._bookmark = bookmark

    @property
    def content_type(self):
        """Gets the content_type of this BundleFile.  # noqa: E501


        :return: The content_type of this BundleFile.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this BundleFile.


        :param content_type: The content_type of this BundleFile.  # noqa: E501
        :type: str
        """
        if content_type is None:
            raise ValueError("Invalid value for `content_type`, must not be `None`")  # noqa: E501

        self._content_type = content_type

    @property
    def hash(self):
        """Gets the hash of this BundleFile.  # noqa: E501


        :return: The hash of this BundleFile.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this BundleFile.


        :param hash: The hash of this BundleFile.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def link(self):
        """Gets the link of this BundleFile.  # noqa: E501


        :return: The link of this BundleFile.  # noqa: E501
        :rtype: Link
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this BundleFile.


        :param link: The link of this BundleFile.  # noqa: E501
        :type: Link
        """

        self._link = link

    @property
    def modified(self):
        """Gets the modified of this BundleFile.  # noqa: E501


        :return: The modified of this BundleFile.  # noqa: E501
        :rtype: int
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this BundleFile.


        :param modified: The modified of this BundleFile.  # noqa: E501
        :type: int
        """
        if modified is None:
            raise ValueError("Invalid value for `modified`, must not be `None`")  # noqa: E501

        self._modified = modified

    @property
    def mount(self):
        """Gets the mount of this BundleFile.  # noqa: E501


        :return: The mount of this BundleFile.  # noqa: E501
        :rtype: Mount
        """
        return self._mount

    @mount.setter
    def mount(self, mount):
        """Sets the mount of this BundleFile.


        :param mount: The mount of this BundleFile.  # noqa: E501
        :type: Mount
        """

        self._mount = mount

    @property
    def mount_path(self):
        """Gets the mount_path of this BundleFile.  # noqa: E501


        :return: The mount_path of this BundleFile.  # noqa: E501
        :rtype: str
        """
        return self._mount_path

    @mount_path.setter
    def mount_path(self, mount_path):
        """Sets the mount_path of this BundleFile.


        :param mount_path: The mount_path of this BundleFile.  # noqa: E501
        :type: str
        """

        self._mount_path = mount_path

    @property
    def name(self):
        """Gets the name of this BundleFile.  # noqa: E501


        :return: The name of this BundleFile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BundleFile.


        :param name: The name of this BundleFile.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def receiver(self):
        """Gets the receiver of this BundleFile.  # noqa: E501


        :return: The receiver of this BundleFile.  # noqa: E501
        :rtype: Receiver
        """
        return self._receiver

    @receiver.setter
    def receiver(self, receiver):
        """Sets the receiver of this BundleFile.


        :param receiver: The receiver of this BundleFile.  # noqa: E501
        :type: Receiver
        """

        self._receiver = receiver

    @property
    def size(self):
        """Gets the size of this BundleFile.  # noqa: E501


        :return: The size of this BundleFile.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this BundleFile.


        :param size: The size of this BundleFile.  # noqa: E501
        :type: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def tags(self):
        """Gets the tags of this BundleFile.  # noqa: E501


        :return: The tags of this BundleFile.  # noqa: E501
        :rtype: dict(str, list[str])
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this BundleFile.


        :param tags: The tags of this BundleFile.  # noqa: E501
        :type: dict(str, list[str])
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags

    @property
    def type(self):
        """Gets the type of this BundleFile.  # noqa: E501


        :return: The type of this BundleFile.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BundleFile.


        :param type: The type of this BundleFile.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def vault_repo(self):
        """Gets the vault_repo of this BundleFile.  # noqa: E501


        :return: The vault_repo of this BundleFile.  # noqa: E501
        :rtype: BundleVaultRepo
        """
        return self._vault_repo

    @vault_repo.setter
    def vault_repo(self, vault_repo):
        """Sets the vault_repo of this BundleFile.


        :param vault_repo: The vault_repo of this BundleFile.  # noqa: E501
        :type: BundleVaultRepo
        """

        self._vault_repo = vault_repo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BundleFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BundleFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
