# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BundleVaultRepo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'added': 'int',
        'id': 'str',
        'mount_id': 'str',
        'name': 'str',
        'path': 'str'
    }

    attribute_map = {
        'added': 'added',
        'id': 'id',
        'mount_id': 'mountId',
        'name': 'name',
        'path': 'path'
    }

    def __init__(self, added=None, id=None, mount_id=None, name=None, path=None):  # noqa: E501
        """BundleVaultRepo - a model defined in Swagger"""  # noqa: E501
        self._added = None
        self._id = None
        self._mount_id = None
        self._name = None
        self._path = None
        self.discriminator = None
        self.added = added
        self.id = id
        self.mount_id = mount_id
        self.name = name
        self.path = path

    @property
    def added(self):
        """Gets the added of this BundleVaultRepo.  # noqa: E501


        :return: The added of this BundleVaultRepo.  # noqa: E501
        :rtype: int
        """
        return self._added

    @added.setter
    def added(self, added):
        """Sets the added of this BundleVaultRepo.


        :param added: The added of this BundleVaultRepo.  # noqa: E501
        :type: int
        """
        if added is None:
            raise ValueError("Invalid value for `added`, must not be `None`")  # noqa: E501

        self._added = added

    @property
    def id(self):
        """Gets the id of this BundleVaultRepo.  # noqa: E501


        :return: The id of this BundleVaultRepo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BundleVaultRepo.


        :param id: The id of this BundleVaultRepo.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def mount_id(self):
        """Gets the mount_id of this BundleVaultRepo.  # noqa: E501


        :return: The mount_id of this BundleVaultRepo.  # noqa: E501
        :rtype: str
        """
        return self._mount_id

    @mount_id.setter
    def mount_id(self, mount_id):
        """Sets the mount_id of this BundleVaultRepo.


        :param mount_id: The mount_id of this BundleVaultRepo.  # noqa: E501
        :type: str
        """
        if mount_id is None:
            raise ValueError("Invalid value for `mount_id`, must not be `None`")  # noqa: E501

        self._mount_id = mount_id

    @property
    def name(self):
        """Gets the name of this BundleVaultRepo.  # noqa: E501


        :return: The name of this BundleVaultRepo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BundleVaultRepo.


        :param name: The name of this BundleVaultRepo.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def path(self):
        """Gets the path of this BundleVaultRepo.  # noqa: E501


        :return: The path of this BundleVaultRepo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this BundleVaultRepo.


        :param path: The path of this BundleVaultRepo.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BundleVaultRepo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BundleVaultRepo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
