# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigMobile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_mobile': 'bool'
    }

    attribute_map = {
        'is_mobile': 'isMobile'
    }

    def __init__(self, is_mobile=None):  # noqa: E501
        """ConfigMobile - a model defined in Swagger"""  # noqa: E501
        self._is_mobile = None
        self.discriminator = None
        self.is_mobile = is_mobile

    @property
    def is_mobile(self):
        """Gets the is_mobile of this ConfigMobile.  # noqa: E501

        IsMobile defines whether user is using a mobile device. It is detected from User-Agent header.  # noqa: E501

        :return: The is_mobile of this ConfigMobile.  # noqa: E501
        :rtype: bool
        """
        return self._is_mobile

    @is_mobile.setter
    def is_mobile(self, is_mobile):
        """Sets the is_mobile of this ConfigMobile.

        IsMobile defines whether user is using a mobile device. It is detected from User-Agent header.  # noqa: E501

        :param is_mobile: The is_mobile of this ConfigMobile.  # noqa: E501
        :type: bool
        """
        if is_mobile is None:
            raise ValueError("Invalid value for `is_mobile`, must not be `None`")  # noqa: E501

        self._is_mobile = is_mobile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigMobile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigMobile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
