# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigMobileAppsAndroid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_gallery_url': 'str',
        'url': 'str'
    }

    attribute_map = {
        'app_gallery_url': 'appGalleryUrl',
        'url': 'url'
    }

    def __init__(self, app_gallery_url=None, url=None):  # noqa: E501
        """ConfigMobileAppsAndroid - a model defined in Swagger"""  # noqa: E501
        self._app_gallery_url = None
        self._url = None
        self.discriminator = None
        if app_gallery_url is not None:
            self.app_gallery_url = app_gallery_url
        self.url = url

    @property
    def app_gallery_url(self):
        """Gets the app_gallery_url of this ConfigMobileAppsAndroid.  # noqa: E501

        AppGalleryUrl is the URL of HUAWEI AppGallery.  # noqa: E501

        :return: The app_gallery_url of this ConfigMobileAppsAndroid.  # noqa: E501
        :rtype: str
        """
        return self._app_gallery_url

    @app_gallery_url.setter
    def app_gallery_url(self, app_gallery_url):
        """Sets the app_gallery_url of this ConfigMobileAppsAndroid.

        AppGalleryUrl is the URL of HUAWEI AppGallery.  # noqa: E501

        :param app_gallery_url: The app_gallery_url of this ConfigMobileAppsAndroid.  # noqa: E501
        :type: str
        """

        self._app_gallery_url = app_gallery_url

    @property
    def url(self):
        """Gets the url of this ConfigMobileAppsAndroid.  # noqa: E501

        Url is the URL of Google Play store.  # noqa: E501

        :return: The url of this ConfigMobileAppsAndroid.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ConfigMobileAppsAndroid.

        Url is the URL of Google Play store.  # noqa: E501

        :param url: The url of this ConfigMobileAppsAndroid.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigMobileAppsAndroid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigMobileAppsAndroid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
