# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FilesListRecursiveItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'ApiErrorDetails',
        'file': 'FilesFile',
        'path': 'str',
        'type': 'str'
    }

    attribute_map = {
        'error': 'error',
        'file': 'file',
        'path': 'path',
        'type': 'type'
    }

    def __init__(self, error=None, file=None, path=None, type=None):  # noqa: E501
        """FilesListRecursiveItem - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._file = None
        self._path = None
        self._type = None
        self.discriminator = None
        if error is not None:
            self.error = error
        if file is not None:
            self.file = file
        if path is not None:
            self.path = path
        self.type = type

    @property
    def error(self):
        """Gets the error of this FilesListRecursiveItem.  # noqa: E501


        :return: The error of this FilesListRecursiveItem.  # noqa: E501
        :rtype: ApiErrorDetails
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this FilesListRecursiveItem.


        :param error: The error of this FilesListRecursiveItem.  # noqa: E501
        :type: ApiErrorDetails
        """

        self._error = error

    @property
    def file(self):
        """Gets the file of this FilesListRecursiveItem.  # noqa: E501


        :return: The file of this FilesListRecursiveItem.  # noqa: E501
        :rtype: FilesFile
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this FilesListRecursiveItem.


        :param file: The file of this FilesListRecursiveItem.  # noqa: E501
        :type: FilesFile
        """

        self._file = file

    @property
    def path(self):
        """Gets the path of this FilesListRecursiveItem.  # noqa: E501

        Path of the file.  # noqa: E501

        :return: The path of this FilesListRecursiveItem.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this FilesListRecursiveItem.

        Path of the file.  # noqa: E501

        :param path: The path of this FilesListRecursiveItem.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def type(self):
        """Gets the type of this FilesListRecursiveItem.  # noqa: E501

        Type is the type of the item.  # noqa: E501

        :return: The type of this FilesListRecursiveItem.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FilesListRecursiveItem.

        Type is the type of the item.  # noqa: E501

        :param type: The type of this FilesListRecursiveItem.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["file", "error"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilesListRecursiveItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilesListRecursiveItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
