# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupUserCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'permissions': 'dict(str, bool)',
        'space_total': 'int'
    }

    attribute_map = {
        'email': 'email',
        'permissions': 'permissions',
        'space_total': 'spaceTotal'
    }

    def __init__(self, email=None, permissions=None, space_total=None):  # noqa: E501
        """GroupUserCreate - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._permissions = None
        self._space_total = None
        self.discriminator = None
        self.email = email
        if permissions is not None:
            self.permissions = permissions
        if space_total is not None:
            self.space_total = space_total

    @property
    def email(self):
        """Gets the email of this GroupUserCreate.  # noqa: E501


        :return: The email of this GroupUserCreate.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GroupUserCreate.


        :param email: The email of this GroupUserCreate.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def permissions(self):
        """Gets the permissions of this GroupUserCreate.  # noqa: E501


        :return: The permissions of this GroupUserCreate.  # noqa: E501
        :rtype: dict(str, bool)
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this GroupUserCreate.


        :param permissions: The permissions of this GroupUserCreate.  # noqa: E501
        :type: dict(str, bool)
        """

        self._permissions = permissions

    @property
    def space_total(self):
        """Gets the space_total of this GroupUserCreate.  # noqa: E501


        :return: The space_total of this GroupUserCreate.  # noqa: E501
        :rtype: int
        """
        return self._space_total

    @space_total.setter
    def space_total(self, space_total):
        """Sets the space_total of this GroupUserCreate.


        :param space_total: The space_total of this GroupUserCreate.  # noqa: E501
        :type: int
        """

        self._space_total = space_total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupUserCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupUserCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
