# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Group(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account': 'GroupAccount',
        'branding': 'GroupBranding',
        'common': 'GroupCommon',
        'id': 'str',
        'name': 'str',
        'permissions': 'dict(str, bool)',
        'users': 'list[GroupUser]'
    }

    attribute_map = {
        'account': 'account',
        'branding': 'branding',
        'common': 'common',
        'id': 'id',
        'name': 'name',
        'permissions': 'permissions',
        'users': 'users'
    }

    def __init__(self, account=None, branding=None, common=None, id=None, name=None, permissions=None, users=None):  # noqa: E501
        """Group - a model defined in Swagger"""  # noqa: E501
        self._account = None
        self._branding = None
        self._common = None
        self._id = None
        self._name = None
        self._permissions = None
        self._users = None
        self.discriminator = None
        if account is not None:
            self.account = account
        self.branding = branding
        if common is not None:
            self.common = common
        self.id = id
        self.name = name
        self.permissions = permissions
        self.users = users

    @property
    def account(self):
        """Gets the account of this Group.  # noqa: E501


        :return: The account of this Group.  # noqa: E501
        :rtype: GroupAccount
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Group.


        :param account: The account of this Group.  # noqa: E501
        :type: GroupAccount
        """

        self._account = account

    @property
    def branding(self):
        """Gets the branding of this Group.  # noqa: E501


        :return: The branding of this Group.  # noqa: E501
        :rtype: GroupBranding
        """
        return self._branding

    @branding.setter
    def branding(self, branding):
        """Sets the branding of this Group.


        :param branding: The branding of this Group.  # noqa: E501
        :type: GroupBranding
        """
        if branding is None:
            raise ValueError("Invalid value for `branding`, must not be `None`")  # noqa: E501

        self._branding = branding

    @property
    def common(self):
        """Gets the common of this Group.  # noqa: E501


        :return: The common of this Group.  # noqa: E501
        :rtype: GroupCommon
        """
        return self._common

    @common.setter
    def common(self, common):
        """Sets the common of this Group.


        :param common: The common of this Group.  # noqa: E501
        :type: GroupCommon
        """

        self._common = common

    @property
    def id(self):
        """Gets the id of this Group.  # noqa: E501


        :return: The id of this Group.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Group.


        :param id: The id of this Group.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501


        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.


        :param name: The name of this Group.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def permissions(self):
        """Gets the permissions of this Group.  # noqa: E501


        :return: The permissions of this Group.  # noqa: E501
        :rtype: dict(str, bool)
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this Group.


        :param permissions: The permissions of this Group.  # noqa: E501
        :type: dict(str, bool)
        """
        if permissions is None:
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions

    @property
    def users(self):
        """Gets the users of this Group.  # noqa: E501


        :return: The users of this Group.  # noqa: E501
        :rtype: list[GroupUser]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this Group.


        :param users: The users of this Group.  # noqa: E501
        :type: list[GroupUser]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Group, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
