# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupBranding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'background_color': 'str',
        'foreground_color': 'str',
        'logo': 'str'
    }

    attribute_map = {
        'background_color': 'backgroundColor',
        'foreground_color': 'foregroundColor',
        'logo': 'logo'
    }

    def __init__(self, background_color=None, foreground_color=None, logo=None):  # noqa: E501
        """GroupBranding - a model defined in Swagger"""  # noqa: E501
        self._background_color = None
        self._foreground_color = None
        self._logo = None
        self.discriminator = None
        if background_color is not None:
            self.background_color = background_color
        if foreground_color is not None:
            self.foreground_color = foreground_color
        if logo is not None:
            self.logo = logo

    @property
    def background_color(self):
        """Gets the background_color of this GroupBranding.  # noqa: E501


        :return: The background_color of this GroupBranding.  # noqa: E501
        :rtype: str
        """
        return self._background_color

    @background_color.setter
    def background_color(self, background_color):
        """Sets the background_color of this GroupBranding.


        :param background_color: The background_color of this GroupBranding.  # noqa: E501
        :type: str
        """

        self._background_color = background_color

    @property
    def foreground_color(self):
        """Gets the foreground_color of this GroupBranding.  # noqa: E501


        :return: The foreground_color of this GroupBranding.  # noqa: E501
        :rtype: str
        """
        return self._foreground_color

    @foreground_color.setter
    def foreground_color(self, foreground_color):
        """Sets the foreground_color of this GroupBranding.


        :param foreground_color: The foreground_color of this GroupBranding.  # noqa: E501
        :type: str
        """

        self._foreground_color = foreground_color

    @property
    def logo(self):
        """Gets the logo of this GroupBranding.  # noqa: E501


        :return: The logo of this GroupBranding.  # noqa: E501
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this GroupBranding.


        :param logo: The logo of this GroupBranding.  # noqa: E501
        :type: str
        """

        self._logo = logo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupBranding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupBranding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
