# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'capacity_max': 'int',
        'users_max': 'int'
    }

    attribute_map = {
        'capacity_max': 'capacityMax',
        'users_max': 'usersMax'
    }

    def __init__(self, capacity_max=None, users_max=None):  # noqa: E501
        """GroupAccount - a model defined in Swagger"""  # noqa: E501
        self._capacity_max = None
        self._users_max = None
        self.discriminator = None
        self.capacity_max = capacity_max
        if users_max is not None:
            self.users_max = users_max

    @property
    def capacity_max(self):
        """Gets the capacity_max of this GroupAccount.  # noqa: E501


        :return: The capacity_max of this GroupAccount.  # noqa: E501
        :rtype: int
        """
        return self._capacity_max

    @capacity_max.setter
    def capacity_max(self, capacity_max):
        """Sets the capacity_max of this GroupAccount.


        :param capacity_max: The capacity_max of this GroupAccount.  # noqa: E501
        :type: int
        """
        if capacity_max is None:
            raise ValueError("Invalid value for `capacity_max`, must not be `None`")  # noqa: E501

        self._capacity_max = capacity_max

    @property
    def users_max(self):
        """Gets the users_max of this GroupAccount.  # noqa: E501


        :return: The users_max of this GroupAccount.  # noqa: E501
        :rtype: int
        """
        return self._users_max

    @users_max.setter
    def users_max(self, users_max):
        """Sets the users_max of this GroupAccount.


        :param users_max: The users_max of this GroupAccount.  # noqa: E501
        :type: int
        """

        self._users_max = users_max

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
