# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SettingsSeen(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'desktop': 'bool',
        'intro': 'bool',
        'office_online': 'bool'
    }

    attribute_map = {
        'desktop': 'desktop',
        'intro': 'intro',
        'office_online': 'officeOnline'
    }

    def __init__(self, desktop=None, intro=None, office_online=None):  # noqa: E501
        """SettingsSeen - a model defined in Swagger"""  # noqa: E501
        self._desktop = None
        self._intro = None
        self._office_online = None
        self.discriminator = None
        if desktop is not None:
            self.desktop = desktop
        if intro is not None:
            self.intro = intro
        if office_online is not None:
            self.office_online = office_online

    @property
    def desktop(self):
        """Gets the desktop of this SettingsSeen.  # noqa: E501


        :return: The desktop of this SettingsSeen.  # noqa: E501
        :rtype: bool
        """
        return self._desktop

    @desktop.setter
    def desktop(self, desktop):
        """Sets the desktop of this SettingsSeen.


        :param desktop: The desktop of this SettingsSeen.  # noqa: E501
        :type: bool
        """

        self._desktop = desktop

    @property
    def intro(self):
        """Gets the intro of this SettingsSeen.  # noqa: E501


        :return: The intro of this SettingsSeen.  # noqa: E501
        :rtype: bool
        """
        return self._intro

    @intro.setter
    def intro(self, intro):
        """Sets the intro of this SettingsSeen.


        :param intro: The intro of this SettingsSeen.  # noqa: E501
        :type: bool
        """

        self._intro = intro

    @property
    def office_online(self):
        """Gets the office_online of this SettingsSeen.  # noqa: E501


        :return: The office_online of this SettingsSeen.  # noqa: E501
        :rtype: bool
        """
        return self._office_online

    @office_online.setter
    def office_online(self, office_online):
        """Sets the office_online of this SettingsSeen.


        :param office_online: The office_online of this SettingsSeen.  # noqa: E501
        :type: bool
        """

        self._office_online = office_online

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SettingsSeen, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SettingsSeen):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
