# coding: utf-8

"""
    DIGI storage API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'has_cloud': 'bool'
    }

    attribute_map = {
        'has_cloud': 'hasCloud'
    }

    def __init__(self, has_cloud=None):  # noqa: E501
        """UserAttributes - a model defined in Swagger"""  # noqa: E501
        self._has_cloud = None
        self.discriminator = None
        self.has_cloud = has_cloud

    @property
    def has_cloud(self):
        """Gets the has_cloud of this UserAttributes.  # noqa: E501


        :return: The has_cloud of this UserAttributes.  # noqa: E501
        :rtype: bool
        """
        return self._has_cloud

    @has_cloud.setter
    def has_cloud(self, has_cloud):
        """Sets the has_cloud of this UserAttributes.


        :param has_cloud: The has_cloud of this UserAttributes.  # noqa: E501
        :type: bool
        """
        if has_cloud is None:
            raise ValueError("Invalid value for `has_cloud`, must not be `None`")  # noqa: E501

        self._has_cloud = has_cloud

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
